name: Deploy to Production

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Google Cloud Platform
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY_PROD }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run (Production)
      run: |
        gcloud run deploy magazine-chat-prod \
          --image gcr.io/$PROJECT_ID/magazine-chat:${{ github.ref_name }} \
          --region your-region \
          --platform managed \
          --no-allow-unauthenticated
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
