name: Deploy to UAT
on:
  push:
    tags:
      - '*-rc'
env:
  SERVICE_NAME_API: ${{ vars.SERVICE_NAME_API }}
  SERVICE_NAME_WEB: ${{ vars.SERVICE_NAME_WEB }}
  GCP_REGION: ${{ vars.GCP_REGION }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract tag name
        id: extract_tag
        run: echo "::set-output name=TAG::${GITHUB_REF#refs/tags/}"
        shell: bash
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Setup gcloud environment
        uses: google-github-actions/setup-gcloud@v2
      - name: Configure Docker
        run: gcloud auth configure-docker
      - name: Build and push Docker image for API
        run: |
          docker build --progress=plain -f src/api/Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME_API }}:${{ steps.extract_tag.outputs.TAG }} ./src/api &&
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME_API }}:${{ steps.extract_tag.outputs.TAG }}
      - name: Build and push Docker image for Web
        run: |
          docker build --progress=plain -f src/web/Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME_WEB }}:${{ steps.extract_tag.outputs.TAG }} ./src/web &&
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME_WEB }}:${{ steps.extract_tag.outputs.TAG }}
      - name: Deploy API to Cloud Run (UAT)
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME_API }} --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME_API }}:${{ steps.extract_tag.outputs.TAG }} --region ${{ env.GCP_REGION }} --platform managed --set-env-vars=ENVIRONMENT=UAT,\
          GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }},\
          GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }},\
          GCP_SEARCH_DATASTORE_ID=${{ secrets.GCP_SEARCH_DATASTORE_ID }},\
          GCP_CHAT_DATASTORE_ID=${{ secrets.GCP_CHAT_DATASTORE_ID }},\
          GOOGLE_PROGRAMMABLE_SEARCH_ENGINE_ID=${{ secrets.GOOGLE_PROGRAMMABLE_SEARCH_ENGINE_ID }},\
          GOOGLE_PROGRAMMABLE_SEARCH_API_KEY=${{ secrets.GOOGLE_PROGRAMMABLE_SEARCH_API_KEY }},\
          AI_SEARCH_ENGINE_ID=${{ secrets.AI_SEARCH_ENGINE_ID }} --allow-unauthenticated --memory 2Gi --timeout=600
      - name: Set API_SERVICE_URL environment variable
        run: echo "API_SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME_API }} --region ${{ env.GCP_REGION }} --platform managed --format 'value(status.url)')" >> $GITHUB_ENV
      - name: Deploy Web to Cloud Run (UAT)
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME_WEB }} --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME_WEB }}:${{ steps.extract_tag.outputs.TAG }} --region ${{ env.GCP_REGION }} --platform managed --set-env-vars=API_SERVICE_URL=${{ env.API_SERVICE_URL }},\
          GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }},\
          AI_CHAT_AGENT_ID=${{ secrets.AI_CHAT_AGENT_ID }} --allow-unauthenticated --memory 2Gi
